kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
        version: v2
    spec:
      containers:
      - name: coffee-shop
        image: sdaschner/coffee-shop:quarkus-istio-ee-2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:8080/health | grep -q coffee-shop"]
      restartPolicy: Always
---
