kind: Service
apiVersion: v1
metadata:
  name: barista
  labels:
    app: barista
spec:
  selector:
    app: barista
  ports:
    - port: 8080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: barista
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: barista
        version: v1
    spec:
      containers:
      - name: barista
        image: sdaschner/barista:quarkus-istio-ee-1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:8080/health | grep -q barista"]
      restartPolicy: Always
---
